get rid of code in main js
add code in greeter.ts

Last login: Mon Jun 18 10:56:25 on ttys001
You have new mail.
cl-pur-w7-04:~ student$ which node
/Users/student/.nvm/versions/node/v10.4.0/bin/node
cl-pur-w7-04:~ student$ which nvm
cl-pur-w7-04:~ student$ nvm install node
Downloading and installing node v10.4.1...
Downloading https://nodejs.org/dist/v10.4.1/node-v10.4.1-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v10.4.1 (npm v6.1.0)
cl-pur-w7-04:~ student$ cd ~/src/node
node/         node_modules/
cl-pur-w7-04:~ student$ cd ~/src/node
cl-pur-w7-04:node student$ ls -a
.			.gitignore		css			index.html		robots.txt
..			.htaccess		doc			js			site.webmanifest
.DS_Store		404.html		favicon.ico		jsconfig.json		tile-wide.png
.editorconfig		LICENSE.txt		humans.txt		node_modules		tile.png
.git			all.min.js		icon.png		package-lock.json
.gitattributes		browserconfig.xml	img			package.json
cl-pur-w7-04:node student$ npm install -g typescript
/Users/student/.nvm/versions/node/v10.4.1/bin/tsc -> /Users/student/.nvm/versions/node/v10.4.1/lib/node_modules/typescript/bin/tsc
/Users/student/.nvm/versions/node/v10.4.1/bin/tsserver -> /Users/student/.nvm/versions/node/v10.4.1/lib/node_modules/typescript/bin/tsserver
+ typescript@2.9.2
added 1 package from 1 contributor in 4.253s
cl-pur-w7-04:node student$ vim js
js/            jsconfig.json
cl-pur-w7-04:node student$ vim js/greeter.ts
cl-pur-w7-04:node student$ tsc js/greeter.ts
cl-pur-w7-04:node student$ ls -a
.			.gitignore		css			index.html		robots.txt
..			.htaccess		doc			js			site.webmanifest
.DS_Store		404.html		favicon.ico		jsconfig.json		tile-wide.png
.editorconfig		LICENSE.txt		humans.txt		node_modules		tile.png
.git			all.min.js		icon.png		package-lock.json
.gitattributes		browserconfig.xml	img			package.json
cl-pur-w7-04:node student$ ls -a js
.		..		.DS_Store	greeter.js	greeter.ts	main.js		plugins.js	vendor
cl-pur-w7-04:node student$ cat js/greeter.js
function greeter(person) {
    return "Hello, " + person;
}
var user = "Jane User";
document.body.innerHTML = greeter(user);
cl-pur-w7-04:node student$ code .
cl-pur-w7-04:node student$ tsc js/greeter.ts
cl-pur-w7-04:node student$ tsc js/greeter.ts
cl-pur-w7-04:node student$ tsc js/greeter.ts
cl-pur-w7-04:node student$ npm install uglifyjs-folder -g
/Users/student/.nvm/versions/node/v10.4.1/bin/uglifyjs-folder -> /Users/student/.nvm/versions/node/v10.4.1/lib/node_modules/uglifyjs-folder/cli.js
+ uglifyjs-folder@1.5.1
added 67 packages from 61 contributors in 12.151s
cl-pur-w7-04:node student$ uglifyjs-folder js -o all.min.js
File all.min.js written successfully !
cl-pur-w7-04:node student$ tsc js/greeter.ts
cl-pur-w7-04:node student$ uglifyjs-folder js -o all.min.js
File all.min.js written successfully !
cl-pur-w7-04:node student$ tsc js/greeter.ts
js/greeter.ts:38:27 - error TS2540: Cannot assign to 'console' because it is a constant or a read-only property.

38     var console = (window.console = window.console || {});
                             ~~~~~~~

cl-pur-w7-04:node student$ tsc js/greeter.ts
cl-pur-w7-04:node student$ uglifyjs-folder js -o all.min.js
File all.min.js written successfully !
cl-pur-w7-04:node student$