uglify js
cl-pur-w7-04:src student$ cd node
node/         node_modules/
cl-pur-w7-04:src student$ cd node
node/         node_modules/
cl-pur-w7-04:src student$ cd node
cl-pur-w7-04:node student$ ls -a
.			.gitattributes		browserconfig.xml	icon.png		robots.txt
..			.gitignore		css			img			site.webmanifest
.DS_Store		.htaccess		doc			index.html		tile-wide.png
.editorconfig		404.html		favicon.ico		js			tile.png
.git			LICENSE.txt		humans.txt		jsconfig.json
cl-pur-w7-04:node student$ npm install gulp
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN saveError ENOENT: no such file or directory, open '/Users/student/src/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/student/src/package.json'
npm WARN src No description
npm WARN src No repository field.
npm WARN src No README data
npm WARN src No license field.

+ gulp@3.9.1
added 129 packages from 73 contributors and audited 23962 packages in 14.289s
found 5 vulnerabilities (1 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
cl-pur-w7-04:node student$ ls -a
.			.gitattributes		browserconfig.xml	icon.png		robots.txt
..			.gitignore		css			img			site.webmanifest
.DS_Store		.htaccess		doc			index.html		tile-wide.png
.editorconfig		404.html		favicon.ico		js			tile.png
.git			LICENSE.txt		humans.txt		jsconfig.json
cl-pur-w7-04:node student$ code .
cl-pur-w7-04:node student$ which gulp
cl-pur-w7-04:node student$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (node) romaineavenue
version: (1.0.0)
description: this is a website
entry point: (index.js)
test command:
git repository: (https://github.com/romaineavenue/romaineavenue.github.io.git)
keywords: javascript, es6
author: Kushal
license: (ISC) GPLv3
Sorry, license should be a valid SPDX license expression (without "LicenseRef"), "UNLICENSED", or "SEE LICENSE IN <filename>" and license is similar to the valid expression "GPL-3.0-or-later".
license: (ISC) GPL-3.0-or-later
About to write to /Users/student/src/node/package.json:

{
  "name": "romaineavenue",
  "version": "1.0.0",
  "description": "this is a website",
  "main": "index.js",
  "directories": {
    "doc": "doc"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/romaineavenue/romaineavenue.github.io.git"
  },
  "keywords": [
    "javascript",
    "es6"
  ],
  "author": "Kushal",
  "license": "GPL-3.0-or-later",
  "bugs": {
    "url": "https://github.com/romaineavenue/romaineavenue.github.io/issues"
  },
  "homepage": "https://github.com/romaineavenue/romaineavenue.github.io#readme"
}

Is this OK? (yes)
cl-pur-w7-04:node student$ npm install gulp
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm notice created a lockfile as package-lock.json. You should commit this file.
+ gulp@3.9.1
added 255 packages from 164 contributors and audited 1119 packages in 11.171s
found 5 vulnerabilities (1 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
cl-pur-w7-04:node student$ npm update

> fsevents@1.2.4 install /Users/student/src/node/node_modules/fsevents
> node install

[fsevents] Success: "/Users/student/src/node/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ gulp@4.0.0
added 198 packages from 109 contributors, removed 64 packages, updated 23 packages and audited 4605 packages in 13.576s
found 0 vulnerabilities

cl-pur-w7-04:node student$ rm -rf node_modules/
cl-pur-w7-04:node student$ npm update

> fsevents@1.2.4 install /Users/student/src/node/node_modules/fsevents
> node install

[fsevents] Success: "/Users/student/src/node/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ gulp@4.0.0
added 389 packages from 234 contributors in 17.206s
cl-pur-w7-04:node student$ npm audit

^C
cl-pur-w7-04:node student$ npm install uglify-js
+ uglify-js@3.4.0
added 3 packages from 38 contributors and audited 4608 packages in 6.692s
found 0 vulnerabilities

cl-pur-w7-04:node student$ uglifyjs --compress --mangle
-bash: uglifyjs: command not found
cl-pur-w7-04:node student$ npm install uglifyjs-folder -g
/Users/student/.nvm/versions/node/v10.4.0/bin/uglifyjs-folder -> /Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/cli.js
+ uglifyjs-folder@1.5.1
added 67 packages from 61 contributors in 5.842s
cl-pur-w7-04:node student$ uglifyjs-folder
.DS_Store          .gitignore         browserconfig.xml  humans.txt         js/                package.json       tile.png
.editorconfig      .htaccess          css/               icon.png           jsconfig.json      robots.txt
.git/              404.html           doc/               img/               node_modules/      site.webmanifest
.gitattributes     LICENSE.txt        favicon.ico        index.html         package-lock.json  tile-wide.png
cl-pur-w7-04:node student$ uglifyjs-folder js
js/            jsconfig.json
cl-pur-w7-04:node student$ uglifyjs-folder js
{ SyntaxError: Unexpected token: name (myParagraph)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
    at formatError (util.js:784:16)
    at formatValue (util.js:615:14)
    at inspect (util.js:328:10)
    at Object.formatWithOptions (util.js:182:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at module.exports (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/index.js:82:15)
    at Object.<anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/cli.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
  message: 'Unexpected token: name (myParagraph)',
  filename: 'main.js',
  line: 2,
  col: 4,
  pos: 18 }

/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/index.js:83
      throw minifyResult.error;
      ^
SyntaxError: Unexpected token: name (myParagraph)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
cl-pur-w7-04:node student$ uglifyjs-folder js
{ SyntaxError: Unexpected token: name (myParagraph)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
    at formatError (util.js:784:16)
    at formatValue (util.js:615:14)
    at inspect (util.js:328:10)
    at Object.formatWithOptions (util.js:182:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at module.exports (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/index.js:82:15)
    at Object.<anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/cli.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
  message: 'Unexpected token: name (myParagraph)',
  filename: 'main.js',
  line: 2,
  col: 4,
  pos: 18 }

/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/index.js:83
      throw minifyResult.error;
      ^
SyntaxError: Unexpected token: name (myParagraph)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
cl-pur-w7-04:node student$ uglifyjs-folder js -o all.min.js
{ SyntaxError: Unexpected token: name (myParagraph)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
    at formatError (util.js:784:16)
    at formatValue (util.js:615:14)
    at inspect (util.js:328:10)
    at Object.formatWithOptions (util.js:182:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at module.exports (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/index.js:82:15)
    at Object.<anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/cli.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
  message: 'Unexpected token: name (myParagraph)',
  filename: 'main.js',
  line: 2,
  col: 4,
  pos: 18 }

/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/index.js:83
      throw minifyResult.error;
      ^
SyntaxError: Unexpected token: name (myParagraph)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/student/.nvm/versions/node/v10.4.0/lib/node_modules/uglifyjs-folder/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
cl-pur-w7-04:node student$ uglifyjs-folder js -o all.min.js
File all.min.js written successfully !
cl-pur-w7-04:node student$ uglifyjs-folder js -o all.min.js
File all.min.js written successfully !
cl-pur-w7-04:node student$